version: "3"
services:
  nginx:
    build: ./docker/nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./app/laravel:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always

  php:
    build: ./docker/php
    volumes:
      - ./app/laravel:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/var_lib_mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d

  node:
    build: ./docker/node
    tty: true
    volumes:
      - ./app/laravel:/var/www/html:cached
    working_dir: /var/www/html

  composer:
    image: composer:2.1.9
    tty: true
    volumes:
      - ./app/laravel:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./docker/minio/data:/export
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Password@1000
    command: [ 'server', '/export', '--console-address', ':9001' ]

  stripe-cli:
    image: stripe/stripe-cli:v1.8.5
    network_mode: host
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
    command: listen --forward-to https://localhost/api/v1/stripe/webhook --skip-verify # 自己証明だと怒られるので「--skip-verify」を指定
